version: "3"

networks:
  backend:
  frontend:

x-app: &app
  build:
    context: .
    args:
      RUBY_VERSION: '3.2.2'
      PG_MAJOR: '15'
      NODE_MAJOR: '18'
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
  tmpfs:
    - /tmp
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  environment: &backend_environment
    <<: *env
    REDIS_URL: redis://redis:6379/0
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: database
    ELASTICSEARCH_HOST: http://elasticsearch:9200
    CHROME_URL: http://chrome:3333
    DOCKER: true
  volumes:
      - .:/app
      - backend_data:/usr/local/bundle
  depends_on: &backend_depends_on
    database:
      condition: service_healthy
    redis:
      condition: service_healthy
    elasticsearch:
      condition: service_started
    chrome:
      condition: service_started
  links:
    - redis
    - elasticsearch
  networks:
    - backend

services:
  database:
    hostname: database-app-container
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    networks:
      - backend
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      - "discovery.type=single-node"
      - "cluster.name=elasticsearch-rails"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=pwd123
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - .conf/elastic/synonyms:/usr/share/elasticsearch/config/synonyms
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - backend
  chrome:
    # Currently, Apple M1 is only supported in unnumbered "latest" versions.
    # See https://github.com/browserless/chrome/issues/1393
    image: browserless/chrome:latest
    ports:
      - "3333:3333"
    # Mount application source code to support file uploading
    # (otherwise Chrome won't be able to find files).
    # NOTE: Make sure you use absolute paths in `#attach_file`.
    volumes:
      - .:/app:cached
    environment:
      # By default, it uses 3000, which is typically used by Rails.
      PORT: 3333
      # Set connection timeout to avoid timeout exception during debugging
      # https://docs.browserless.io/docs/docker.html#connection-timeout
      CONNECTION_TIMEOUT: 600000
    networks:
      - backend
  web:
    <<: *backend
    hostname: web-app-container
    ports:
      - "3000:3000"
    depends_on:
      sidekiq:
        condition: service_started
    networks:
      - backend
      - frontend
  sidekiq:
    <<: *backend
    hostname: sidekiq-app-container
    command: /app/bin/bundle exec sidekiq
  redis:
    image: docker.io/redis:latest
    hostname: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - .conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  backend_data:
  database-data:
    driver: local
  elasticsearch_data:
